version: '3.8'

services:
  mysql:
    container_name: mysqldb
    image: "mysql:latest"
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      spring-boot-mysql-network:
  spring-app:
    container_name: spring-app
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/hello_docker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345aaa
    networks:
      spring-boot-mysql-network:

volumes:
  db:

networks:
  spring-boot-mysql-network:
